### ISSUE TITLE
Assignment 1 is ready

### ISSUE THREAD

**Issue by gabrielslimcoll** [VIS-2129-F2020/cvoulgaris-vis#1]
Both the .Rmd file and the html file are ready (no need for grading since I'm auditing). I hope I did this right! 

I don't see any option to assign this on the right. I'm also not sure I'm even supposed to submit this since I'm auditing. But, it was helpful to learn this process for the first time! @c-voulgaris  

[Link to assignment 1](https://gabrielslimcoll.github.io/vis-2129/assignment-1).
https://github.com/gabrielslimcoll/vis-2129/edit/master/README.md

**Comment by c-voulgaris** [comment]
Thanks!

You're meant to assign the issue to me on your own repo. For students enrolled in the class, we've created repos for them in the class org. We'll create one for you as well - watch for an invitation in the coming days.
